Create Footer Component - MariaD 11.27.24
Code-the-Dream-School/hh-team1-front pull request #18
Opened 2024-11-27 07:14 UTC by tobemari

closes #15 
This PR introduces a Footer component to centralize styling across the app.
Centralizing styling simplifies future design updates.

Key changes:
- Added a footer for branding and user engagement.

2024-12-02 23:34 UTC, umavenki commented on src/Theme.jsx
> +export default theme;
Theme looks good Maria. I see the same in PR https://github.com/Code-the-Dream-School/hh-team1-front/pull/17. Are you planning to merge Theme with this PR or the other one?

2024-12-03 06:06 UTC, StuvaScript requested changes
All of this code looks great!!

One request though. Can you push all the files that you've updated please. I had to do some digging around the internet to find and download all the dependencies and get the ThemeProvider component working to use the theme and check out the Footer component. That way we can have an easy merge to see all your good work :)

2024-12-03 21:04 UTC, StuvaScript approved these changes

2024-12-03 21:08 UTC, StuvaScript commented
Oh wow, lots of great work! The only thing I had an issue with was in the Theme.jsx file I couldn't find the origin of the "@fontSource/Inter/400.css" import. But other than that this looks amazing!

2024-12-06 16:11 UTC, tobemari commented
> Oh wow, lots of great work! The only thing I had an issue with was in the Theme.jsx file I couldn't find the origin of the "@fontSource/Inter/400.css" import. But other than that this looks amazing!

Hey Stu, I got the problem. I installed that package with command `npm install @fontsource/inter` instead of `npm install @fontsource/inter --save`, that's why you did't find it in the package.json. I did it with right command and pushed changes

2024-12-11 22:51 UTC, jgoldenberg29 approved these changes
Layout looks good to me! way to put in the work Mariia. There will most likely be some merge conflicts between all 4 of you especially in the app.jsx so make sure you all communicate about which code should remain.

2024-12-12 20:13 UTC, tobemari commented
> Layout looks good to me! way to put in the work Mariia. There will most likely be some merge conflicts between all 4 of you especially in the app.jsx so make sure you all communicate about which code should remain.

Thank you Josh! I'll do the communication

2024-12-12 20:46 UTC, merged