Add itineray functions stu 12.17.24
Code-the-Dream-School/hh-team1-front pull request #39
Opened 2024-12-21 23:23 UTC by StuvaScript

2024-12-30 17:09 UTC, jgoldenberg29 requested changes
Great work here Stu! My only suggestion is, I think we could have more specific/descriptive names for our request functions - what kind of data are we posting and patching etc.?

2024-12-30 20:44 UTC, jgoldenberg29 approved these changes

2024-12-30 23:14 UTC, nihalerdal approved these changes
Approved Stu! Everything is structured effectively with helpful examples. Easy to follow.

2024-12-31 00:17 UTC, nihalerdal commented
Not sure, but using special characters like "&" in the file name might cause issues in some environments. Just a suggestion to rename it for better compatibility😊

2025-01-02 20:14 UTC, merged